name: Maven Test

on:
  push:
    branches:
      - master

jobs:
  mvn_test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      - name: Build With Maven
      	run: mvn --batch-mode --update-snapshots verify
      	
