name: Maven Test

on:
  push:
    branches:
      - master

jobs:
  mvn_test:
    name: Testing
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master

      # - name: Javascript testing
      #   run: yarn test

      - name: Maven Clean
      	run: mvn clean
      	
      - name: Maven Install
      	run: mvn install
      	
      - name: Maven Test
      	run: mvn test
